# Generated by Django 4.2.5 on 2023-09-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='content',
        ),
        migrations.AddField(
            model_name='articles',
            name='body',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='conclusion',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='intro',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date_posted',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
