# Generated by Django 4.2.5 on 2023-09-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_remove_articles_content_articles_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
