# Generated by Django 4.2.5 on 2023-09-20 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0010_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='conclusion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='intro',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
