# Generated by Django 4.2.5 on 2023-09-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0012_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='body',
            new_name='body1',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='title',
            new_name='title1',
        ),
        migrations.AddField(
            model_name='articles',
            name='body2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='image2',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
